version: '3.8'

services:
  # fit3170_usability_accessibility_testing_app:
  #   build: .
  #   image: web
  #   container_name: web
  #   ports:
  #     - 5005:5000
  #   command: python app.py
  #   volumes:
  #     - .:/usr/src/app
  #   environment:
  #     - FLASK_DEBUG=1
  #     - REDIS_URL=redis://redis:6379/0
  #     - MONGO_URL=mongodb://username:password@mongodb
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - redis
  #     - mongodb

  web:
      build: .
      privileged: true
      ports:
          - "5002:5002"
      volumes:
          - .:/usr/src/app
      depends_on:
          - redis
          - mongodb

  worker:
    build: .
    command: celery worker #--app=project.server.tasks.celery --loglevel=info
    container_name: worker
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=project.server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
    container_name: redis

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
