version: '3.8'
services:
  web2:
    build: .
    image: web
    container_name: web
    ports:
      - 5005:5000
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/FIT3170_Usability_Accessibility_Testing_App/
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URL=mongodb://localhost:27017/

    depends_on:
      - redis
      - mongodb

  react-ui:
    build:
      context: ./Website
    ports:
      - "3001:3001"
    container_name: react-ui
    stdin_open: true
    volumes:
       - .:/usr/src/FIT3170_Usability_Accessibility_Testing_App/Website
       - .:/usr/src/FIT3170_Usability_Accessibility_Testing_App/Website/node_modules

  emulator:
    tty: true
    build: .
    container_name: android-container
    privileged: true
    image: budtmo/docker-android-x86-8.1
    ports:
      - 6080:6080
      - 5554:5554
      - 5555:5555
    environment:
      - DEVICE=Samsung Galaxy S6


  worker:
    build: .
    command: celery worker --app=server.tasks.celery --loglevel=info
    volumes:
      - .:/usr/src/FIT3170_Usability_Accessibility_Testing_App/
    environment:
      - FLASK_DEBUG=1
      - APP_SETTINGS=server.config.DevelopmentConfig
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/0
      - MONGO_URL=mongodb://username:password@mongodb
    depends_on:
      - web2
      - redis

  # dashboard:
  #   build: .
  #   command:  flower --app=project.server.tasks.celery --port=5555 --broker=redis://redis:6379/0
  #   ports:
  #     - 5558:5555
  #   environment:
  #     - FLASK_DEBUG=1
  #     - APP_SETTINGS=project.server.config.DevelopmentConfig
  #     - CELERY_BROKER_URL=redis://redis:6379/0
  #     - CELERY_RESULT_BACKEND=redis://redis:6379/0
  #   depends_on:
  #     - web2
  #     - redis
  #     - worker

  mongodb:
    tty: true
    image: mongo:5.0
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - .:/data/mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password

  
  redis:
    image: redis:6-alpine
