# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "ci-cd", "master", "main", "#merge_branch", "#setup-cicd" ]
  pull_request:
    branches: [ "ci-cd", "master", "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Set up Python 3.8.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.9"
    - name: cd into flask_backend directory
      run: |
        cd server
    - name: Install dependencies
      run: |
        cd server
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        cd server
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: UnitTest with pytest
      run: |
        docker-compose up -d --build localstack
        docker-compose up -d --build flask_backend
        docker-compose up -d --build mongodb
        docker-compose exec -T flask_backend pip3 install pytest
        docker-compose exec -T flask_backend pytest
